name: complex-workflow

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date
  
  windows:
    runs-on: windows-latest
    steps:
      - run: date

  macos:
    runs-on: macos-latest
    steps:
      - run: date

  job4:
    runs-on: ubuntu-latest
    needs: [ubuntu, macos, windows]
    steps:
      - run: date
      - run: echo "This is the final job in the workflow."